site_name:        Devices.jl
repo_url:         https://github.com/PainterQubits/Devices.jl
site_description: Package for designing CAD files for superconducting devices.
site_author:      Andrew Keller

theme: material
extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - admonition

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Points: points.md
- Polygons: polygons.md
- Cells: cells.md
- Paths: paths.md
- Compound shapes: shapes.md
- Rendering: render.md
- File formats: fileio.md
- 'License': LICENSE.md
